# Header
menu:
  Home: /
  Archives: /archives
  About: /about
#rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
#- tag
- links
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /css/images/qrcode4assert1024.jpg
twitter:
google_plus:
fb_admins:
fb_app_id: